#!/bin/bash

python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_0 --lamb 0
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_50 --lamb 50
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100
python route_using_model.py --model ./model/lambda_100 --lamb 100